### ISSUE TITLE
Horiz Bar Chart Y-Axis names not wrapping

### ISSUE THREAD

**Issue by mrainville1618** [BadMonkeysTeam/Mandrill#30] opened 2017-02-24 22:53 UTC
Am I missing something for how to achieve wrapping in the y-axis titles? I see it working in your example, although I am sending it info from the Warning.ErrorMessage node thru List.CountOccurances and not directly from a CSV.

[Uploading Pages from Horiz-Bar_Title-Wrap-Question.pdf…]()

**Comment by ksobon** [comment] 2017-02-25 03:36
I can't see what the problem is. PDF was not posted properly. Can you repost as Image?

**Comment by mrainville1618** [comment] 2017-02-25 15:52
OK! it wasn't working last time, but this time it is. I submitted an additional .png of the definition at the end because the jpg isn't the best resolution. I hope this shows what I am experiencing. Thank you for making this project! I am excited to make use of it to help our users visualize their warnings.

Is there a justification or alignment parameter I am missing?

![horiz-bar_title-wrap-question page 001](https://cloud.githubusercontent.com/assets/20841797/23332467/d8fd47ac-fb2e-11e6-9555-fd16ddde7381.jpg)
![horiz-bar_title-wrap-question page 002](https://cloud.githubusercontent.com/assets/20841797/23332468/d8fd6868-fb2e-11e6-917c-71217d6493a8.jpg)
![datavis_warning-rating-dyn](https://cloud.githubusercontent.com/assets/20841797/23332469/d8fd9982-fb2e-11e6-9249-5912deeded21.png)

**Comment by ksobon** [comment] 2017-02-25 16:07
The image is Dynamo definition is not high enough resolution for me to make out what is going on in there. I am going to take a wild guess though. Did you try making the left margin smaller? It looks to me that it's set to some really large value. Also, this word wrapping was added recently so make sure you have the latest version of Mandrill from the Package Manager.

**Comment by mrainville1618** [comment] 2017-02-28 14:34
I just checked and the bottom dyn def image is clear. I tried making the margin smaller, was only large because I was trying to find the max length of warning. I am getting closer to an overall solution, although I am beginning to think it is an issue that the project I was testing on is in rvt2015, and I know there are differences in how nodes can function or what nodes are available between 15 and 17. Also, I do have the latest mandrill package. Thank you for checking, I will continue to tinker with it when I have time.

**Comment by ksobon** [comment] 2017-03-18 19:17
Were you ever able to get it to work? If you are on the latest Mandrill, that margin value does look about right, and Revit version should not matter at all because you are not connecting directly to Revit, just an HTML file that was produced from Revit, then I am running out of options. If you want to post the DYN/HTML/CSV files so I can re-create it on my machine, then maybe we can get this solved. Apologies for a delay. I have been a little busy lately.

**Comment by mrainville1618** [comment] 2017-03-20 13:55
Honestly, I have also been very busy and not able to devote time back to this task. I will try another time to recreate the process and see if I just missed something. I had uninstalled the previous mandrill package and a few related packages and reinstalled them (which I really hope Dynamo developers will revamp the package system). I can post what I had from the initial run.
[horizontalBarChart.zip](https://github.com/BadMonkeysTeam/Mandrill/files/855145/horizontalBarChart.zip)

**Comment by mrainville1618** [comment] 2017-03-20 13:57
No rush in the least, I am merely wondering what I did wrong or what happened. I would like to make use of this for our teams. Thank you again for making this package and supporting those like me who ask for  assistance.

**Comment by ksobon** [comment] 2017-03-23 01:47
I can't open that file. It's saying its corrupted: 

![image](https://cloud.githubusercontent.com/assets/529781/24228127/99ed2bc6-0f48-11e7-884c-31420c0ae42e.png)

I did however open the error library file that you sent me. it's basically the 900 errors that i posted on my website and said explicitly not to use. The reason I said that is because as most of these will work there are some on that list that are just a template and not actual errors. I would actually recommend to compile your own list of known errors. Anyways, this might not be needed soon as Revit 2018 will have Warnings accessible via API and that will render these HTML reports useless. :-) 

I am not sure why the file is corrupted but can you do me a favor and disconnect your report and window nodes before saving? It's just a hunch but worth trying. Can you then post the file again? 

Cheers!

**Comment by ksobon** [comment] 2017-05-07 02:22
This should be fixed in the last release. Please let me know if it's still an issue and i will reopen it.

**Closed by ksobon** 2017-05-07 02:22 UTC
Labels: help wanted
